# Generated by Django 5.2.4 on 2025-08-05 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='petspecies',
            options={'verbose_name_plural': 'Pet species'},
        ),
        migrations.RemoveField(
            model_name='petspecies',
            name='description',
        ),
    ]
