# Generated by Django 5.2.4 on 2025-08-13 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_eggpet_species'),
    ]

    operations = [
        migrations.AddField(
            model_name='petspecies',
            name='evolved_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
